<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chattarin Poungtubtim (cpoungtubtim@ucsd.edu)">
<meta name="dcterms.date" content="2025-12-10">

<title>Replication of Study Tracking the relation between gist and item memory over the course of long-term memory consolidation by Tima Zeng et al.&nbsp;(2021, eLife)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Replication Report Template_files/libs/clipboard/clipboard.min.js"></script>
<script src="Replication Report Template_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Replication Report Template_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Replication Report Template_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Replication Report Template_files/libs/quarto-html/popper.min.js"></script>
<script src="Replication Report Template_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Replication Report Template_files/libs/quarto-html/anchor.min.js"></script>
<link href="Replication Report Template_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Replication Report Template_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Replication Report Template_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Replication Report Template_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Replication Report Template_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#power-analysis" id="toc-power-analysis" class="nav-link" data-scroll-target="#power-analysis">Power Analysis</a></li>
  <li><a href="#planned-sample" id="toc-planned-sample" class="nav-link" data-scroll-target="#planned-sample">Planned Sample</a></li>
  <li><a href="#materials" id="toc-materials" class="nav-link" data-scroll-target="#materials">Materials</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan">Analysis Plan</a></li>
  <li><a href="#reliability-and-validity" id="toc-reliability-and-validity" class="nav-link" data-scroll-target="#reliability-and-validity">Reliability and validity</a></li>
  <li><a href="#differences-from-original-study" id="toc-differences-from-original-study" class="nav-link" data-scroll-target="#differences-from-original-study">Differences from Original Study</a></li>
  <li><a href="#methods-addendum-post-data-collection" id="toc-methods-addendum-post-data-collection" class="nav-link" data-scroll-target="#methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data preparation</a></li>
  <li><a href="#confirmatory-analysis" id="toc-confirmatory-analysis" class="nav-link" data-scroll-target="#confirmatory-analysis">Confirmatory analysis</a></li>
  <li><a href="#exploratory-analyses" id="toc-exploratory-analyses" class="nav-link" data-scroll-target="#exploratory-analyses">Exploratory analyses</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-of-replication-attempt" id="toc-summary-of-replication-attempt" class="nav-link" data-scroll-target="#summary-of-replication-attempt">Summary of Replication Attempt</a></li>
  <li><a href="#commentary" id="toc-commentary" class="nav-link" data-scroll-target="#commentary">Commentary</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of Study Tracking the relation between gist and item memory over the course of long-term memory consolidation by Tima Zeng et al.&nbsp;(2021, eLife)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chattarin Poungtubtim (cpoungtubtim@ucsd.edu) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 10, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The current project aims to replicate findings from experiment 1 of Zeng et al ., 2021. Firstly, they found that while item memories of spatial landmarks become more noisy and have higher errors over time, gist memory or the average location of all landmarks remains relatively stable. As gist memory is stable and has higher representational strength, it could influence the recall of item memory so that the location of recalled landmark is attracted toward the gist location. This effect could be observed in memory bias. Crucially, the study found that memory bias becomes more attracted toward the gist after 1 month delay period.</p>
<p>Link to the paper : https://github.com/CP-PP8/Zeng2021/blob/main/original_paper/elife-65588-v3.pdf Link to the repository : https://github.com/CP-PP8/Zeng2021/tree/main Link to the pre-regsitration : https://osf.io/a4nk5 Link to the experiment : Session 1 : https://github.com/psyc-201/Zeng2021/blob/main/experiment/gist_bias_phase1/index.html Session 2 :https://github.com/psyc-201/Zeng2021/blob/main/experiment/gist_bias_phase2/index.html</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="power-analysis" class="level3">
<h3 class="anchored" data-anchor-id="power-analysis">Power Analysis</h3>
<p>They do not report any effect size in the paper. On average, they have around 40 participants for each group. So the total number of subjects that we have to collect will be around 120-130 subjects to replicate the full effect size.</p>
</section>
<section id="planned-sample" class="level3">
<h3 class="anchored" data-anchor-id="planned-sample">Planned Sample</h3>
<p>120-130 subjects from UCSD psychology undergraduate students and separate them into 3 different groups Exclusion criteria =&gt; bad performance compared to group average : lower than 3 SD below average in any testing sessions (in either individual or gist memory trials) =&gt; bads performance on gist trial : if the gist response is located outside the boundary of learned landmarks =&gt; drop out of second session</p>
</section>
<section id="materials" class="level3">
<h3 class="anchored" data-anchor-id="materials">Materials</h3>
<p>The experiment will be built as described in Zeng et al.&nbsp;using JSPsych. Here, there are slight modification as we are planning to collect experimental data online. The screensize of the task will be fixed to 1200 * 640 pixels for all participants</p>
<p>The stimuli used in this study will be black dot presented on the screen. Each dot is corresponded to a name of different places such as hospital, school. The dot will be presented sequentially and location of each of them will be different on the screen. So participants need to remember the match between the dot location and the place it represents e.g.&nbsp;A hospital is a dot located on the upper right. The training phase will let participants to learn an association between the location and name of the place. They will have to learn a set of 6 dots-location pairings in total. The first phase of training is an exposure to dot-location pair. Participants will learn the association and proceed to next item by clicking on the screen. Each pair will be presented sequentially. There is no time-limit in this phase. Next, they will proceed to the second phase training, here they have to recall the location of dot cued by name of the place (university ?). After they respond, they will receive a feedback. If the response error is less than 80 pixel from true location, they will receive a feedback telling the correct location of that dot and proceed to the next dot. If they made a bigger error than 80 pixels, then they will have 2 more attempts to answer the correct answer. The location of the dot will be shown at feedback if they make 3 incorrect attempts. Lastly, they proceed to phase 3 of the training phase. In this phase, They have to recall each landmark consecutively and must have a smaller error than 80 pixels for all items to progress to the test phase. If not, they will go back to session 2 for more training. After the finish training phase 3. They will have to perform unrelated arithmetric problem to reduce an effect of longering memories before going into the test phase. Then they will have to return for another testing sessions and each participant will be allocated to different duration between test session 1 and 2 : at 1 day, 1 week and 1 month after the training phase. For each test trial, participants will be showned a dot of on screen and the name of a place. Then they will need to answer the location and the name are correctly matched. There will be one extra trial that asks participants to report an average location of all dots they learned during the training phase. Here, I plan to replicate experiment 1 in this study</p>
</section>
<section id="procedure" class="level3">
<h3 class="anchored" data-anchor-id="procedure">Procedure</h3>
<p>Experiment : During training phase 1, a dot with a size of 15 pixels will be presented along the text displaying the landmark corresponding to the dot. For phase 2, the landmark text will be displared on the screen and participants need to click on the location that they think represent the dot. Nexy, the feedback will be shown and participants learned the correct location of a landamark. For training phase 3, the trial proceeds in the similar manner to phase 2 but there is no feedback. The testing session is also proceed in the same pattern as training phase 3 but there will be an additional trial asking for participants to respond for aan average location of all landmarks in the set they’ve just learned. The location of dots will be the same across participants. Only mapping between dot location and landmark name would change across participants, The behavioral response will be collected by recording the position (x,y) that participants click on the screen during each trials. Reaction time is also collected for possible additional analysis</p>
<p>Participants will be recruited online via SONA system. In session 1, they will have to finish 3 training phases and unrelated arithmetric task in order to start the testing phase. After they finish the 1st session, they would be asked to return for 2nd session at varied intervals. Here, they will receive a credit when they are done with 2 sessions.</p>
</section>
<section id="analysis-plan" class="level3">
<h3 class="anchored" data-anchor-id="analysis-plan">Analysis Plan</h3>
<p>Error measurement =&gt; individual item : the error would be calculated as the Euclidean distance from participant’s report to the correct location and then average across all 6 locations to get item memory error for each participant. =&gt; gist memory : there are 2 ways of estimating gist memory error. First, we would calculate the euclidean distance between reported gist and the true gist location. The second method is to caluclate reported gist by averaging over all participant’s response on individual memroy to get estimated gist. The we could calculate distance between two fo them just like the first method.</p>
<p>Bias measurement The bias would be defined as the difference between the Euclidean distance from true item location to true gist location and the Euclidean distance from reported item location to true gist location divided by the Euclidean distance from true item location to true gist location. If the bias is more than 0, it means that there is an attractive bias toward the gist location</p>
<p>Bias simulation</p>
<p>There are 2 simulation for bias here: item-only bias and item-gist bias. The item-only bias is simulated by using error for each items as the distance from the true location and simulate the angular distance uniformly from 0-360 degree. Each simulation run consists of 6 items and average bias will be calculated. Then we will run a simulation for 1000 runs and get average bias over all runs. Finally, we would iterate over participants and get populatio bias. For item-gist bias, they would be a slight adjustment on how we sample angular distance. Now, the distribution will not be uniform and probability on sampling each angle bin (we bin 360 deg. angular space into 200 bins) will be depending on how close it is to the reported center.</p>
<p>Statistics</p>
<p>To test how gist and item memory errors change over time, we would perform 3 (time interval : 24 hr, 1 week, 1 month) x 2 (item memory, gist memory) aligned ranks transformation ANOVA. Futheremore, we will use two-tailed Mann-Whitney tests to compare error change between groups To compare whether observed bias is different from simulated item-only bias over time, we conducted a 2 (session: Session 1 vs.&nbsp;Session 2) x 3 (delay groups: 24 hr, 1 week, and 1 month) ANOVA. Next we will use two-tailed paired t-tests for post-hoc comparison. Lastly, we will use the same statistical tests 2 x 3 ANOVA and two-tailed pair t-tests to determine whether observe bias become more similar simulated gist-based bias overtime.</p>
</section>
<section id="reliability-and-validity" class="level3">
<h3 class="anchored" data-anchor-id="reliability-and-validity">Reliability and validity</h3>
<p>The method to measure an error is calculating euclidean distance on x and y-axis. It has been used widely in spatial memory research and has a validity. However, the reliability in this study might be lower than other research as they only measure memory for each location once. So it is more likely to have a noisy estimation of memory from single measurement.</p>
<p>Normally, the measurement of memory bias can be vary. Some studies use a proportion of response that is biased toward other items. Other studies might flip the sign of error based on the direction of bias and calculate circular mean of error distribution and see whether a mean is significantly different from 0. In this study, they calculate bias by using the difference between the Euclidean distance from true item location to true gist location and the Euclidean distance from reported item location to true gist location divided by the Euclidean distance from true item location to true gist location. It is more similar to the first method but here they also scale bias so it should be affected less by any outliers. The only concern here is that the reliability might be low as previously mentioned. Another concern is that there is no baseline to compare bias. Therefore, they use simulated bias in order to compare whether the bias become closer to gist overtime.</p>
</section>
<section id="differences-from-original-study" class="level3">
<h3 class="anchored" data-anchor-id="differences-from-original-study">Differences from Original Study</h3>
<p>Instead of collecting data onsite like in original paper, we collect data online via SONA system. In doing so, we make the change so that the screen size remains the same across all computers by setting canvas size as 1200 * 640 pixels (1280 * 800 pixels in original paper). From the feedback of pilot study, we also added feedback for every responses during phase 2 of training.</p>
</section>
<section id="methods-addendum-post-data-collection" class="level3">
<h3 class="anchored" data-anchor-id="methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</h3>
<p>As the data collection is incompleted, the statistical test needs to be changed from the original study. Here, we will use 2 x 2 ANOVA to o see whether the interaction between memory types (item vs gist) and sessions (1 vs 2) is significant. The same test is also applied to memory biases with different factor conditions (bias types : observed vs simulated bias , sessions)</p>
<section id="actual-sample" class="level4">
<h4 class="anchored" data-anchor-id="actual-sample">Actual Sample</h4>
<p>In the end, we collected 52 participants who completed both session 1 and 2 (36 participants dropped out and did not participate in session 2). After using exclusion criteria as mentioned in the original study, only 36 participantss were included in the final analysis.</p>
</section>
<section id="differences-from-pre-data-collection-methods-plan" class="level4">
<h4 class="anchored" data-anchor-id="differences-from-pre-data-collection-methods-plan">Differences from pre-data collection methods plan</h4>
<p>Here, due to time constraint, we only collected data from 24 hour group instead of 1 week or 1 month group.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data preparation</h3>
<p>Data preparation following the analysis plan.</p>
<div id="1058864b" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import python libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.stats <span class="im">as</span> stats</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pingouin <span class="im">as</span> pg</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Import dataframe </span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Change path </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>datapath <span class="op">=</span> <span class="st">'/Users/chattarinpoungtubtim/Zeng2021/analysis/all_sub_data.csv'</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>all_sub_df <span class="op">=</span> pd.read_csv(datapath)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Get data as numpy array</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">## Item memory errors for session 1 and 2</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>all_error_ind_s1 <span class="op">=</span> all_sub_df[<span class="st">'avg_ind_error_session_1'</span>].to_numpy()</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>all_error_ind_s2 <span class="op">=</span> all_sub_df[<span class="st">'avg_ind_error_session_2'</span>].to_numpy()</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">## Gist memory errors for session 1 and 2</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>all_error_gist_s1 <span class="op">=</span> all_sub_df[<span class="st">'gist_error_session_1'</span>].to_numpy()</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>all_error_gist_s2 <span class="op">=</span> all_sub_df[<span class="st">'gist_error_session_2'</span>].to_numpy()</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">## Gist response conditions for session 1 and 2 (is the response lie within the boundary)</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>all_good_gist_s1 <span class="op">=</span> all_sub_df[<span class="st">'good_gist_loc_session_1'</span>].to_numpy()</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>all_good_gist_s2 <span class="op">=</span> all_sub_df[<span class="st">'good_gist_loc_session_2'</span>].to_numpy()</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Exclude data</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">## exclusion criteria 1 : bad item memory performance compared to group</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">### session 1 check</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>all_avg_error_ind_s1 <span class="op">=</span> np.median(all_error_ind_s1)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>all_std_error_ind_s1 <span class="op">=</span> np.std(all_error_ind_s1)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>low_error_ind_s1 <span class="op">=</span> all_avg_error_ind_s1<span class="op">+</span> (<span class="dv">3</span> <span class="op">*</span> all_std_error_ind_s1)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co">### session 2 check</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>all_avg_error_ind_s2 <span class="op">=</span> np.median(all_error_ind_s2)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>all_std_error_ind_s2 <span class="op">=</span> np.std(all_error_ind_s2)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>low_error_ind_s2 <span class="op">=</span> all_avg_error_ind_s2 <span class="op">+</span> (<span class="dv">3</span> <span class="op">*</span> all_std_error_ind_s2)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co">## exclusion criteria 2 : bad item memory performance compared to group</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co">### session 1 check</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>all_avg_error_gist_s1 <span class="op">=</span> np.median(all_error_gist_s1)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>all_std_error_gist_s1 <span class="op">=</span> np.std(all_error_gist_s1)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>low_error_gist_s1 <span class="op">=</span> all_avg_error_gist_s1 <span class="op">+</span> (<span class="dv">3</span> <span class="op">*</span> all_std_error_gist_s1)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co">### session 2 check</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>all_avg_error_gist_s2 <span class="op">=</span> np.median(all_error_gist_s2)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>all_std_error_gist_s2 <span class="op">=</span> np.std(all_error_gist_s2)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>low_error_gist_s2 <span class="op">=</span> all_avg_error_gist_s2 <span class="op">+</span> (<span class="dv">3</span> <span class="op">*</span> all_std_error_gist_s2)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="co">## combine 1 and 2</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>good_avg_perf_s1 <span class="op">=</span> np.logical_and(all_error_ind_s1 <span class="op">&lt;=</span> low_error_ind_s1, all_error_gist_s1 <span class="op">&lt;=</span> low_error_gist_s1)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>good_avg_perf_s2 <span class="op">=</span> np.logical_and(all_error_ind_s2  <span class="op">&lt;=</span> low_error_ind_s2, all_error_gist_s2 <span class="op">&lt;=</span> low_error_gist_s2)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>good_avg_perf_all <span class="op">=</span> np.logical_and(good_avg_perf_s1,good_avg_perf_s2)</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="co">## combine with good gist response</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>good_gist_both <span class="op">=</span> np.logical_and(all_good_gist_s1,all_good_gist_s2)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>good_sub_all <span class="op">=</span> np.logical_and(good_avg_perf_all,good_gist_both)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a><span class="co">## get clean subjects</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>ID_good_sub <span class="op">=</span> all_sub_df[<span class="st">'ID_sub'</span>].to_numpy()[good_sub_all]</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="co">## get clean dataframe</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>clean_sub_df <span class="op">=</span> all_sub_df[all_sub_df[<span class="st">'ID_sub'</span>].isin(ID_good_sub)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="statistical-test-for-memory-error" class="level4">
<h4 class="anchored" data-anchor-id="statistical-test-for-memory-error">Statistical test for memory error</h4>
<div id="1afddc2d" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prepare for stat tests for memory error</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>error_df <span class="op">=</span> clean_sub_df[[<span class="st">'ID_sub'</span>,<span class="st">'avg_ind_error_session_1'</span>,<span class="st">'avg_ind_error_session_2'</span>,<span class="st">'gist_error_session_1'</span>,<span class="st">'gist_error_session_2'</span>]]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># copy dataframe</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>error_cop <span class="op">=</span> error_df.copy()</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">## melt dataframe before doing stat tests</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>error_melt <span class="op">=</span> pd.melt(error_cop,id_vars<span class="op">=</span><span class="st">'ID_sub'</span>,value_vars<span class="op">=</span>[<span class="st">'avg_ind_error_session_1'</span>,<span class="st">'avg_ind_error_session_2'</span>,<span class="st">'gist_error_session_1'</span>,<span class="st">'gist_error_session_2'</span>])</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">## create 2 factor conditons (sessions x memory types)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>session_cond <span class="op">=</span> []</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>mem_cond <span class="op">=</span> []</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">### mem cond - 0 : ind, 1 : gist</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">### session cond - 1 : 0, 2 : 1</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(error_melt[<span class="st">'ID_sub'</span>])):</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> error_melt[<span class="st">'variable'</span>][i] <span class="op">==</span> <span class="st">'avg_ind_error_session_1'</span>:</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">0</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        mem_cond.append(<span class="dv">0</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> error_melt[<span class="st">'variable'</span>][i] <span class="op">==</span> <span class="st">'avg_ind_error_session_2'</span>:</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">1</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>        mem_cond.append(<span class="dv">0</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> error_melt[<span class="st">'variable'</span>][i] <span class="op">==</span> <span class="st">'gist_error_session_1'</span>:</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">0</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>        mem_cond.append(<span class="dv">1</span>) </span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: </span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">1</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>        mem_cond.append(<span class="dv">1</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>error_melt[<span class="st">'session_cond'</span>] <span class="op">=</span> session_cond</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>error_melt[<span class="st">'mem_cond'</span>] <span class="op">=</span> mem_cond</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 x 2 anova for memory error</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>aov_error <span class="op">=</span> pg.rm_anova(data<span class="op">=</span>error_melt, dv<span class="op">=</span><span class="st">'value'</span>,subject <span class="op">=</span><span class="st">'ID_sub'</span>, within<span class="op">=</span>[<span class="st">'session_cond'</span>,<span class="st">'mem_cond'</span>], correction<span class="op">=</span><span class="va">False</span>, effsize<span class="op">=</span><span class="st">"np2"</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="co">## print result for ANOVA</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">' 2 x 2 ANOVA for memory errors (sessions vs memory types)'</span>)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>pg.print_table(aov_error)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="co"># post hoc paired t-test for memory error</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="co">## get difference of memory error between session 2 and 1 for both item and gist memories</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>diff_err_ind <span class="op">=</span> error_df[<span class="st">'avg_ind_error_session_2'</span>].to_numpy() <span class="op">-</span> error_df[<span class="st">'avg_ind_error_session_1'</span>].to_numpy()</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>diff_err_gist <span class="op">=</span> error_df[<span class="st">'gist_error_session_2'</span>].to_numpy() <span class="op">-</span> error_df[<span class="st">'gist_error_session_1'</span>].to_numpy()</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>t_stats, p_val <span class="op">=</span> stats.ttest_rel(diff_err_ind,diff_err_gist)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a><span class="co">## get degree of freedom</span></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>t_df <span class="op">=</span> np.<span class="bu">sum</span>(good_sub_all)<span class="op">-</span><span class="dv">1</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="co">## effect size : Cohen's D</span></span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>cohen_d_err <span class="op">=</span> np.mean(diff_err_ind<span class="op">-</span>diff_err_gist)<span class="op">/</span>np.std(diff_err_ind<span class="op">-</span>diff_err_gist)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="co">## print result</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'post-hoc t-test for memory error differences (item vs gist) : t(</span><span class="sc">{</span>t_df<span class="sc">}</span><span class="ss">) = </span><span class="sc">{</span>t_stats<span class="sc">}</span><span class="ss">, p = </span><span class="sc">{</span>p_val<span class="sc">}</span><span class="ss">, Cohens D = </span><span class="sc">{</span>cohen_d_err<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2 x 2 ANOVA for memory errors (sessions vs memory types)

=============
ANOVA SUMMARY
=============

Source                           SS    ddof1    ddof2          MS       F    p-unc    p-GG-corr    np2    eps
-----------------------  ----------  -------  -------  ----------  ------  -------  -----------  -----  -----
session_cond             155004.248        1       34  155004.248  49.100    0.000        0.000  0.591  1.000
mem_cond                  43607.127        1       34   43607.127  12.731    0.001        0.001  0.272  1.000
session_cond * mem_cond   53624.310        1       34   53624.310  21.918    0.000        0.000  0.392  1.000

post-hoc t-test for memory error differences (item vs gist) : t(34) = 4.681652095722693, p = 4.426437775837793e-05, Cohens D = 0.8028967105459032</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/chattarinpoungtubtim/Library/Python/3.9/lib/python/site-packages/pingouin/distribution.py:507: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  data.groupby(level=1, axis=1, observed=True, group_keys=False)
/Users/chattarinpoungtubtim/Library/Python/3.9/lib/python/site-packages/pingouin/distribution.py:507: FutureWarning: DataFrameGroupBy.diff with axis=1 is deprecated and will be removed in a future version. Operate on the un-grouped DataFrame instead
  data.groupby(level=1, axis=1, observed=True, group_keys=False)</code></pre>
</div>
</div>
</section>
<section id="statistical-test-for-memory-bias" class="level4">
<h4 class="anchored" data-anchor-id="statistical-test-for-memory-bias">statistical test for memory bias</h4>
<div id="c8410c58" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prepare for stat tests for memory bias</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>bias_df <span class="op">=</span> clean_sub_df[[<span class="st">'ID_sub'</span>,<span class="st">'obs_bias_session_1'</span>,<span class="st">'obs_bias_session_2'</span>,<span class="st">'sim_bias_session_1'</span>,<span class="st">'sim_bias_session_2'</span>]]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># copy dataframe</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>bias_cop <span class="op">=</span> bias_df.copy()</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">## melt dataframe before doing stat tests</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>bias_melt <span class="op">=</span> pd.melt(bias_cop,id_vars<span class="op">=</span><span class="st">'ID_sub'</span>,value_vars<span class="op">=</span>[<span class="st">'obs_bias_session_1'</span>,<span class="st">'obs_bias_session_2'</span>,<span class="st">'sim_bias_session_1'</span>,<span class="st">'sim_bias_session_2'</span>])</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">## create 2 factor conditons (sessions x memory types)</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>session_cond <span class="op">=</span> []</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>bias_cond <span class="op">=</span> []</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">### bias cond - 0 : observed, 1 : simulated</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">### session cond - 1 : 0, 2 : 1</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(bias_melt[<span class="st">'ID_sub'</span>])):</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> bias_melt[<span class="st">'variable'</span>][i] <span class="op">==</span> <span class="st">'obs_bias_session_1'</span>:</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">0</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>        bias_cond.append(<span class="dv">0</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> bias_melt[<span class="st">'variable'</span>][i] <span class="op">==</span> <span class="st">'obs_bias_session_2'</span>:</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">1</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        bias_cond.append(<span class="dv">0</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> bias_melt[<span class="st">'variable'</span>][i] <span class="op">==</span> <span class="st">'sim_bias_session_1'</span>:</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">0</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>        bias_cond.append(<span class="dv">1</span>) </span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: </span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>        session_cond.append(<span class="dv">1</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>        bias_cond.append(<span class="dv">1</span>)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>bias_melt[<span class="st">'session_cond'</span>] <span class="op">=</span> session_cond</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>bias_melt[<span class="st">'bias_cond'</span>] <span class="op">=</span> bias_cond</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 x 2 anova for memory bias</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>aov_bias <span class="op">=</span> pg.rm_anova(data<span class="op">=</span>bias_melt, dv<span class="op">=</span><span class="st">'value'</span>,subject <span class="op">=</span><span class="st">'ID_sub'</span>, within<span class="op">=</span>[<span class="st">'session_cond'</span>,<span class="st">'bias_cond'</span>], correction<span class="op">=</span><span class="va">False</span>, effsize<span class="op">=</span><span class="st">"np2"</span>)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co">## print result for ANOVA</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">' 2 x 2 ANOVA for memory biases (sessions vs memory types)'</span>)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>pg.print_table(aov_bias)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="co"># post hoc paired t-test for memory biases</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="co">## compare memory bias between session 1 and 2 </span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>t_stats_ses, p_val_ses <span class="op">=</span> stats.ttest_rel(bias_df[<span class="st">'obs_bias_session_2'</span>].to_numpy(),bias_df[<span class="st">'obs_bias_session_1'</span>].to_numpy())</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="co">## get degree of freedom</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>t_df_ses <span class="op">=</span> np.<span class="bu">sum</span>(good_sub_all)<span class="op">-</span><span class="dv">1</span></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="co">## effect size : Cohen's D</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>diff_bias_ses <span class="op">=</span> bias_df[<span class="st">'obs_bias_session_2'</span>].to_numpy()<span class="op">-</span>bias_df[<span class="st">'obs_bias_session_1'</span>].to_numpy()</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>cohen_d_bias_ses <span class="op">=</span> np.mean(diff_bias_ses)<span class="op">/</span>np.std(diff_bias_ses)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a><span class="co">## print result</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'post-hoc t-test for memory biases difference over time (phase 1 vs phase 2) : t(</span><span class="sc">{</span>t_df_ses<span class="sc">}</span><span class="ss">) = </span><span class="sc">{</span>t_stats_ses<span class="sc">}</span><span class="ss">, p = </span><span class="sc">{</span>p_val_ses<span class="sc">}</span><span class="ss">, Cohens D = </span><span class="sc">{</span>cohen_d_bias_ses<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="co">## compare memory bias between observed and simulated at session 1 </span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>t_stats_sim1, p_val_sim1 <span class="op">=</span> stats.ttest_rel(bias_df[<span class="st">'obs_bias_session_1'</span>].to_numpy(),bias_df[<span class="st">'sim_bias_session_1'</span>].to_numpy())</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a><span class="co">## get degree of freedom</span></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>t_df_sim1 <span class="op">=</span> np.<span class="bu">sum</span>(good_sub_all)<span class="op">-</span><span class="dv">1</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a><span class="co">## effect size : Cohen's D</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>diff_bias_sim1 <span class="op">=</span> bias_df[<span class="st">'obs_bias_session_1'</span>].to_numpy()<span class="op">-</span>bias_df[<span class="st">'sim_bias_session_1'</span>].to_numpy()</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>cohen_d_bias_sim1 <span class="op">=</span> np.mean(diff_bias_sim1)<span class="op">/</span>np.std(diff_bias_sim1)</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="co">## print result</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'post-hoc t-test for memory biases difference at session 1 (observed vs simulated) : t(</span><span class="sc">{</span>t_df_sim1<span class="sc">}</span><span class="ss">) = </span><span class="sc">{</span>t_stats_sim1<span class="sc">}</span><span class="ss">, p = </span><span class="sc">{</span>p_val_sim1<span class="sc">}</span><span class="ss">, Cohens D = </span><span class="sc">{</span>cohen_d_bias_sim1<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a><span class="co">## compare memory bias between observed and simulated at session 2 </span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>t_stats_sim2, p_val_sim2 <span class="op">=</span> stats.ttest_rel(bias_df[<span class="st">'obs_bias_session_2'</span>].to_numpy(),bias_df[<span class="st">'sim_bias_session_2'</span>].to_numpy())</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a><span class="co">## get degree of freedom</span></span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>t_df_sim2 <span class="op">=</span> np.<span class="bu">sum</span>(good_sub_all)<span class="op">-</span><span class="dv">1</span></span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a><span class="co">## effect size : Cohen's D</span></span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>diff_bias_sim2 <span class="op">=</span> bias_df[<span class="st">'obs_bias_session_2'</span>].to_numpy()<span class="op">-</span>bias_df[<span class="st">'sim_bias_session_2'</span>].to_numpy()</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>cohen_d_bias_sim2 <span class="op">=</span> np.mean(diff_bias_sim2)<span class="op">/</span>np.std(diff_bias_sim2)</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a><span class="co">## print result</span></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'post-hoc t-test for memory biases difference at session 2 (observed vs simulated) : t(</span><span class="sc">{</span>t_df_sim2<span class="sc">}</span><span class="ss">) = </span><span class="sc">{</span>t_stats_sim2<span class="sc">}</span><span class="ss">, p = </span><span class="sc">{</span>p_val_sim2<span class="sc">}</span><span class="ss">, Cohens D = </span><span class="sc">{</span>cohen_d_bias_sim2<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 2 x 2 ANOVA for memory biases (sessions vs memory types)

=============
ANOVA SUMMARY
=============

Source                       SS    ddof1    ddof2     MS       F    p-unc    p-GG-corr    np2    eps
------------------------  -----  -------  -------  -----  ------  -------  -----------  -----  -----
session_cond              0.127        1       34  0.127   2.968    0.094        0.094  0.080  1.000
bias_cond                 0.555        1       34  0.555   7.795    0.009        0.009  0.187  1.000
session_cond * bias_cond  0.791        1       34  0.791  15.384    0.000        0.000  0.312  1.000

post-hoc t-test for memory biases difference over time (phase 1 vs phase 2) : t(34) = 1.449054546995651, p = 0.15648355813408496, Cohens D = 0.2485108046040732
post-hoc t-test for memory biases difference at session 1 (observed vs simulated) : t(34) = -0.4047623516573586, p = 0.6881875358785569, Cohens D = -0.0694161706281916
post-hoc t-test for memory biases difference at session 2 (observed vs simulated) : t(34) = 4.769479707755545, p = 3.411669224497952e-05, Cohens D = 0.8179590217459823</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/Users/chattarinpoungtubtim/Library/Python/3.9/lib/python/site-packages/pingouin/distribution.py:507: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  data.groupby(level=1, axis=1, observed=True, group_keys=False)
/Users/chattarinpoungtubtim/Library/Python/3.9/lib/python/site-packages/pingouin/distribution.py:507: FutureWarning: DataFrameGroupBy.diff with axis=1 is deprecated and will be removed in a future version. Operate on the un-grouped DataFrame instead
  data.groupby(level=1, axis=1, observed=True, group_keys=False)</code></pre>
</div>
</div>
</section>
<section id="plot-result" class="level4">
<h4 class="anchored" data-anchor-id="plot-result">Plot result</h4>
<div id="d64086a9" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># function for plotting errors</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_bar_and_scatter(data1,data2,title,labels,ylabel,color<span class="op">=</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="dv">0</span>, <span class="dv">1</span>),bar_width<span class="op">=</span><span class="fl">0.4</span>,capsize<span class="op">=</span><span class="dv">12</span>,ylim<span class="op">=</span><span class="dv">350</span>):</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.arange(<span class="dv">0</span>,<span class="bu">len</span>(labels))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">#get mean across conditions (within subjects)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    mean_data <span class="op">=</span> (data1 <span class="op">+</span> data2) <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">#demean both data</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    demean_data1 <span class="op">=</span> data1 <span class="op">-</span> mean_data</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    demean_data2 <span class="op">=</span> data2 <span class="op">-</span> mean_data</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">#get mean</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    mean_data <span class="op">=</span> [np.mean(data1), np.mean(data2)]</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">#get std error</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    std_error_data <span class="op">=</span> [np.std(demean_data1), np.std(demean_data2)]</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="co">#set up plot</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> [color, color] </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot bar</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    ax.bar(x,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>       height<span class="op">=</span>mean_data,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>       yerr<span class="op">=</span>std_error_data,    <span class="co"># error bars</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>       capsize<span class="op">=</span><span class="dv">12</span>, <span class="co"># error bar cap width in points</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>       width<span class="op">=</span>bar_width,    <span class="co"># bar width</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>       tick_label<span class="op">=</span>labels,</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>       color<span class="op">=</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>),  <span class="co"># face color transparent</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>       edgecolor<span class="op">=</span>colors</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>       )</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    <span class="co">#plot scatter</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    ax.scatter(x[<span class="dv">0</span>] <span class="op">+</span> np.random.random(data1.size) <span class="op">*</span> bar_width <span class="op">-</span> bar_width <span class="op">/</span> <span class="dv">2</span>, data1, color<span class="op">=</span>colors[<span class="dv">0</span>],alpha<span class="op">=</span><span class="fl">0.5</span>)   </span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    ax.scatter(x[<span class="dv">1</span>] <span class="op">+</span> np.random.random(data2.size) <span class="op">*</span> bar_width <span class="op">-</span> bar_width <span class="op">/</span> <span class="dv">2</span>, data2, color<span class="op">=</span>colors[<span class="dv">1</span>],alpha<span class="op">=</span><span class="fl">0.5</span>)  </span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    plt.title(title)</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(ylabel)</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    plt.ylim(<span class="dv">0</span>,ylim)</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a><span class="co">#plot data for item errors</span></span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>data1 <span class="op">=</span> all_error_ind_s1[good_sub_all]</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>data2 <span class="op">=</span> all_error_ind_s2[good_sub_all]</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>title <span class="op">=</span> <span class="st">'item error for both sessions (24 hr delay)'</span></span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">'session 1'</span>, <span class="st">'session 2'</span>]</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a>ylabel <span class="op">=</span> <span class="st">'error (pixels)'</span></span>
<span id="cb8-42"><a href="#cb8-42" aria-hidden="true" tabindex="-1"></a>plot_bar_and_scatter(data1,data2,title,labels,ylabel)</span>
<span id="cb8-43"><a href="#cb8-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-44"><a href="#cb8-44" aria-hidden="true" tabindex="-1"></a><span class="co">#plot data for gist errors</span></span>
<span id="cb8-45"><a href="#cb8-45" aria-hidden="true" tabindex="-1"></a>data1 <span class="op">=</span> all_error_gist_s1[good_sub_all]</span>
<span id="cb8-46"><a href="#cb8-46" aria-hidden="true" tabindex="-1"></a>data2 <span class="op">=</span> all_error_gist_s2[good_sub_all]</span>
<span id="cb8-47"><a href="#cb8-47" aria-hidden="true" tabindex="-1"></a>title <span class="op">=</span> <span class="st">'gist error for both sessions (24 hr delay)'</span></span>
<span id="cb8-48"><a href="#cb8-48" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">'session 1'</span>, <span class="st">'session 2'</span>]</span>
<span id="cb8-49"><a href="#cb8-49" aria-hidden="true" tabindex="-1"></a>ylabel <span class="op">=</span> <span class="st">'error (pixels)'</span></span>
<span id="cb8-50"><a href="#cb8-50" aria-hidden="true" tabindex="-1"></a>color <span class="op">=</span> (<span class="fl">0.4</span>, <span class="dv">0</span>, <span class="fl">0.8</span>, <span class="dv">1</span>)</span>
<span id="cb8-51"><a href="#cb8-51" aria-hidden="true" tabindex="-1"></a>plot_bar_and_scatter(data1,data2,title,labels,ylabel,color)</span>
<span id="cb8-52"><a href="#cb8-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-53"><a href="#cb8-53" aria-hidden="true" tabindex="-1"></a><span class="co">#get bias data and exclude poor performers</span></span>
<span id="cb8-54"><a href="#cb8-54" aria-hidden="true" tabindex="-1"></a>all_obs_bias_s1 <span class="op">=</span> all_sub_df[<span class="st">'obs_bias_session_1'</span>].to_numpy()[good_sub_all]</span>
<span id="cb8-55"><a href="#cb8-55" aria-hidden="true" tabindex="-1"></a>all_obs_bias_s2 <span class="op">=</span> all_sub_df[<span class="st">'obs_bias_session_2'</span>].to_numpy()[good_sub_all]</span>
<span id="cb8-56"><a href="#cb8-56" aria-hidden="true" tabindex="-1"></a>all_sim_bias_s1 <span class="op">=</span> all_sub_df[<span class="st">'sim_bias_session_1'</span>].to_numpy()[good_sub_all]</span>
<span id="cb8-57"><a href="#cb8-57" aria-hidden="true" tabindex="-1"></a>all_sim_bias_s2 <span class="op">=</span> all_sub_df[<span class="st">'sim_bias_session_2'</span>].to_numpy()[good_sub_all]</span>
<span id="cb8-58"><a href="#cb8-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-59"><a href="#cb8-59" aria-hidden="true" tabindex="-1"></a><span class="co"># get mean and std error for observed bias (both sessions)</span></span>
<span id="cb8-60"><a href="#cb8-60" aria-hidden="true" tabindex="-1"></a>avg_obs_bias_both <span class="op">=</span> (all_obs_bias_s1  <span class="op">+</span> all_obs_bias_s2 )<span class="op">/</span><span class="dv">2</span></span>
<span id="cb8-61"><a href="#cb8-61" aria-hidden="true" tabindex="-1"></a>demean_obs_bias_s1 <span class="op">=</span> all_obs_bias_s1  <span class="op">-</span> avg_obs_bias_both</span>
<span id="cb8-62"><a href="#cb8-62" aria-hidden="true" tabindex="-1"></a>demean_obs_bias_s2 <span class="op">=</span> all_obs_bias_s2   <span class="op">-</span> avg_obs_bias_both</span>
<span id="cb8-63"><a href="#cb8-63" aria-hidden="true" tabindex="-1"></a>mean_obs_bias_both_sess <span class="op">=</span> [np.mean(all_obs_bias_s1), np.mean(all_obs_bias_s2)]</span>
<span id="cb8-64"><a href="#cb8-64" aria-hidden="true" tabindex="-1"></a>std_obs_bias_both_sess <span class="op">=</span> [np.std(demean_obs_bias_s1), np.std(demean_obs_bias_s2)]</span>
<span id="cb8-65"><a href="#cb8-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-66"><a href="#cb8-66" aria-hidden="true" tabindex="-1"></a><span class="co"># get mean and std error for simulated bias (both sessions)</span></span>
<span id="cb8-67"><a href="#cb8-67" aria-hidden="true" tabindex="-1"></a>avg_sim_bias_both <span class="op">=</span> (all_sim_bias_s1  <span class="op">+</span> all_sim_bias_s2 )<span class="op">/</span><span class="dv">2</span></span>
<span id="cb8-68"><a href="#cb8-68" aria-hidden="true" tabindex="-1"></a>demean_sim_bias_s1 <span class="op">=</span> all_sim_bias_s1  <span class="op">-</span> avg_sim_bias_both</span>
<span id="cb8-69"><a href="#cb8-69" aria-hidden="true" tabindex="-1"></a>demean_sim_bias_s2 <span class="op">=</span> all_sim_bias_s2   <span class="op">-</span> avg_sim_bias_both</span>
<span id="cb8-70"><a href="#cb8-70" aria-hidden="true" tabindex="-1"></a>mean_sim_bias_both_sess <span class="op">=</span> [np.mean(all_sim_bias_s1), np.mean(all_sim_bias_s2)]</span>
<span id="cb8-71"><a href="#cb8-71" aria-hidden="true" tabindex="-1"></a>std_sim_bias_both_sess <span class="op">=</span> [np.std(demean_sim_bias_s1), np.std(demean_sim_bias_s2)]</span>
<span id="cb8-72"><a href="#cb8-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-73"><a href="#cb8-73" aria-hidden="true" tabindex="-1"></a><span class="co"># plot data for memory bias</span></span>
<span id="cb8-74"><a href="#cb8-74" aria-hidden="true" tabindex="-1"></a>bar_w <span class="op">=</span> <span class="fl">0.2</span></span>
<span id="cb8-75"><a href="#cb8-75" aria-hidden="true" tabindex="-1"></a>x_int <span class="op">=</span> np.arange(<span class="bu">len</span>(labels))</span>
<span id="cb8-76"><a href="#cb8-76" aria-hidden="true" tabindex="-1"></a>plt.bar(x_int<span class="op">+</span>bar_w, mean_obs_bias_both_sess, yerr<span class="op">=</span>std_obs_bias_both_sess, width<span class="op">=</span>bar_w, label<span class="op">=</span><span class="st">'observed bias'</span>, color<span class="op">=</span><span class="st">'red'</span>)</span>
<span id="cb8-77"><a href="#cb8-77" aria-hidden="true" tabindex="-1"></a>plt.bar(x_int<span class="op">-</span>bar_w, mean_sim_bias_both_sess, yerr<span class="op">=</span>std_sim_bias_both_sess,  width<span class="op">=</span>bar_w, label<span class="op">=</span><span class="st">'simulated bias'</span>, color<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb8-78"><a href="#cb8-78" aria-hidden="true" tabindex="-1"></a>plt.xticks(x_int,labels)</span>
<span id="cb8-79"><a href="#cb8-79" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="dv">0</span>,linestyle<span class="op">=</span><span class="st">'--'</span>,color<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb8-80"><a href="#cb8-80" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="op">-</span><span class="fl">0.5</span>,<span class="fl">0.5</span>)</span>
<span id="cb8-81"><a href="#cb8-81" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'memory bias across session'</span>)</span>
<span id="cb8-82"><a href="#cb8-82" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb8-83"><a href="#cb8-83" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Replication%20Report%20Template_files/figure-html/cell-5-output-1.png" width="593" height="431" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Replication%20Report%20Template_files/figure-html/cell-5-output-2.png" width="593" height="431" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="Replication%20Report%20Template_files/figure-html/cell-5-output-3.png" width="582" height="431" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="confirmatory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="confirmatory-analysis">Confirmatory analysis</h3>
<p>First, we examined whether item memories have more increase in error over time compared to gist memories. Here we used 2 x 2 ANOVA to see whether the interaction between memory types (item vs gist) and sessions (1 vs 2) is significant. 2 x 2 ANOVA found the significant interaction between these two factors : F(1,34) = 21.918, p &lt; 0.001 suggesting that item and gist memories error change differently over time. Then, to confirm that gist memory remains more stable over time while item memories become more noisy, we used post-hoc paired t-test to compared the difference of memory from session 1 to 2 between gist and item memories. We found the significant difference between them : T(34) = 4.68, p &lt; 0.001 and Cohen’s d 0.8. In summary, we could replicate the difference between gist and item memory over time.</p>
<section id="zeng-et-al.-2021-graph-memory-error" class="level4">
<h4 class="anchored" data-anchor-id="zeng-et-al.-2021-graph-memory-error">Zeng et al., 2021 Graph (memory error)</h4>
<p><img src="./Fig/Zeng_Ori_MemErr.jpg" class="img-fluid"></p>
</section>
<section id="replication-graph-memory-error" class="level4">
<h4 class="anchored" data-anchor-id="replication-graph-memory-error">Replication Graph (memory error)</h4>
<p><img src="./Fig/Zeng_Rep_MemErr.png" class="img-fluid"></p>
<p>Crucially, we want to replicate whether the memory bias of each item becomes more attract toward the gist over time. In a similar manner to previous analysis, we used 2 x 2 ANOVA to see whether the interaction between bias types (observed vs simulated) and sessions (1 vs 2)</p>
</section>
<section id="zeng-et-al.-2021-graph-memory-bias" class="level4">
<h4 class="anchored" data-anchor-id="zeng-et-al.-2021-graph-memory-bias">Zeng et al., 2021 Graph (memory bias)</h4>
<p><img src="./Fig/Zeng_Ori_MemBias.jpg" class="img-fluid"></p>
</section>
<section id="replication-graph-memory-bias" class="level4">
<h4 class="anchored" data-anchor-id="replication-graph-memory-bias">Replication Graph (memory bias)</h4>
<p><img src="./Fig/Zeng_Rep_MemBias.png" class="img-fluid"></p>
</section>
</section>
<section id="exploratory-analyses" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-analyses">Exploratory analyses</h3>
<p>Contrary to previous studies on gist memory, here we found that gist memory is worse than item memory in session 1. Here, we suspect that participants might misunderstood the instruction and tried to response closer to the screen center. Instead of calculating gist memory error using gist location, we used screen center as the target. We found that calculating gist memory error based on screen center results in lower gist memory error.</p>
<p><img src="./Fig/Zeng_Rep_GistSwap.png" class="img-fluid"></p>
<p>As we found earlier that participants might misunderstood the instruction or did something differently from simply reporting the gist. There is another way to evaluate gist memory by combining all reported location of each item and generating reported gist location. Here, we found that the reported gist generated by this method is very close to the true gist. Suggesting that participants still have an accurate representation of gist memory.</p>
<p><img src="./Fig/Zeng_Rep_GistResp.png" class="img-fluid"></p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="summary-of-replication-attempt" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-replication-attempt">Summary of Replication Attempt</h3>
<p>From collecting data after 24 hour delay, we found that gist memory is relatively more stable than item memory as there is a smaller increase of memory error for gist compared to item memory. According to the original study, we would not expect to find attractio bias toward the gist after 24 hour as they only found it 1 month after session 1. In our replication study, we found a trend that memory error becomes more attracted toward the gist but it is not significant. However, if we compare observed bias to simulated bias. Then we could see the bias is “attracted” toward the gist memory in session 2. As time goes by, simulated bias will become more repulsive as item memory error increases. Therefore, we should expect memory bias to be more repulsive over time if there is no attraction toward the gist. But here, we found increasing albeit not significant bias toward the gist in session 2 and it is higher than simulated bias. Suggesting that there could be attraction bias toward the gist memory. Overall, the result from this replication study is far from conclusive but points toward similar results in the original study</p>
</section>
<section id="commentary" class="level3">
<h3 class="anchored" data-anchor-id="commentary">Commentary</h3>
<p>In this replication study, we could only partially replicate findings from the original study as we only have result from 24 hour group. However,we found similar findings to the original such as relatively more stable gist memory compared to item memory over time and attraction bias toward the gist memory after a delay. Furthermore, we also observed a non-significanttrend that memory bias becomes more attracted to gist memory over time.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>