---
title: "Replication of Study Tracking the relation between gist and item memory over the course of long-term memory consolidation by Tima Zeng et al. (2021, eLife)"
author: "Chattarin Poungtubtim (cpoungtubtim@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

The reason I chose this paper to replicate is that I want to investiage the connection between the rate of representational drift in hippocampus and  the transition from detailed episodic memory to more abstract gist-like memory. In this paper, they studied how the spatial memory of locations became more attracted to the gist or an average of all location over time. Here I would  use this as an behavioral experiment and combine it with neuroimaging technique such as fMRI to track how neural representation of spatial memories correlate with gist-like transformation of the memory. The behavioral result we expect to see the increasing of gist-based bias of individual item memories as times go by. For the future plan, I would like to explore this bias to related to a direction of drift of memory representation in the brain. 

Link to the paper : https://github.com/CP-PP8/Zeng2021/blob/main/original_paper/elife-65588-v3.pdf
Link to the repository : https://github.com/CP-PP8/Zeng2021/tree/main





## Methods 

The stimuli used in this study will be black dot presented on the screen. Each dot is corresponded to a name of different places such as hospital, school. The dot will be presented sequentially and location of each of them will be different on the screen. So participants need to remember the match between the dot location and the place it represents e.g. A hospital is a dot located on the upper right. The training phase will let participants to learn an association between the location and name of the place. They will have to learn a set of 6 dots-location pairings in total. The first phase of training is an exposure to dot-location pair. Participants will learn the association and proceed to next item by clicking on the screen. Each pair will be presented sequentially. There is no time-limit in this phase. Next, they will proceed to the second phase training, here they have to recall the location of dot cued by name of the place (university ?). After they respond, they will receive a feedback. If the response error is less than 80 pixel from true location, they will receive a feedback telling the correct location of that dot and proceed to the next dot. If they made a bigger error than 80 pixels, then they will have 2 more attempts to answer the correct answer. The location of the dot will be shown at feedback if they make 3 incorrect attempts. Lastly, they proceed to phase 3 of the training phase. In this phase, They have to recall each landmark consecutively and must have a smaller error than 80 pixels for all items to progress to the test phase. If not, they will go back to session 2 for more training. After the finish training phase 3. They will have to perform unrelated arithmetric problem to reduce an effect of longering memories before going into the test phase. Then they will have to return for another testing sessions and each participant will be  allocated to different duration between test session 1 and 2 : at 1 day, 1 week and 1 month after the training phase. For each test trial, participants will be showned a dot of on screen and the name of a place. Then they will need to answer the location and the name are correctly matched. There will be one extra trial that asks participants to report an average location of all dots they learned during the training phase. Here, I plan to replicate experiment 1 in this study



### Power Analysis

They do not report any effect size in the paper. On average, they have around 40 participants for each group. So the total number of subjects that we have to collect will be around 120-130 subjects to replicate the full effect size. 

### Planned Sample

90-100 subjects from UCSD psychology undergraduate students and separate them into 3 different groups
Exclusion criteria
=> bad performance compared to group average : lower than 3 SD below average in any testing sessions (in either individual or gist memory trials)
=> bads performance compared on gist trial : if the gist response is located outside the boundary of learned landmarks
=> drop out of second session

### Materials 
The experiment will be built as exactly as described in Zeng et al. using JSPsych 


### Procedure 
Experiment :  During training phase 1, a dot with a size of 15 pixels will be presented along the text displaying the landmark corresponding to the dot. For phase 2, the landmark text will be displared on the screen and participants need to click on the location that they think represent the dot. Nexy, the feedback will be shown and participants learned the correct location of a landamark. For training phase 3, the trial proceeds in the similar manner to phase 2 but there is no feedback. The testing session is also proceed in the same pattern as training phase 3 but there will be an additional trial asking for participants to respond for aan average location of all landmarks in the set they've just learned. The location of dots will be the same across participants. Only mapping between dot location and landmark name would change across participants, The behavioral response will be collected by recording the position (x,y) that participants click on the screen during each trials. Reaction time is also collected for possible additional analysis

Participants will be recruited online via SONA system. In session 1, they will have to finish 3 training phases and unrelated arithmetric task in order to start the testing phase. After they finish the 1st session, they would be asked to return for 2nd session at varied intervals. Here, they will receive a credit when they are done with 2 sessions. 


### Analysis Plan

Error measurement
=> individual item : the error would be calculated as the Euclidean distance from participant's report to the correct location and then average across all 6 locations to get item memory error for each participant.
=> gist memory : there are 2 ways of estimating gist memory error. First, we would calculate the euclidean distance between reported gist and the true gist location. The second method is to caluclate reported gist by averaging over all participant's response on individual memroy to get estimated gist. The we could calculate distance between two fo them just like the first method.

Bias measurement
The bias would be defined as the difference between the Euclidean distance from true item location to true gist location and the Euclidean distance from reported item location to true gist location divided by the Euclidean distance from true item location to true gist location. If the bias is more than 0, it means that there is an attractive bias toward the gist location

Bias simulation

There are 2 simulation for bias here: item-only bias and item-gist bias. The item-only bias is simulated by using error for each items as the distance from the true location and simulate the angular distance uniformly from 0-360 degree. Each simulation run consists of 6 items and average bias will be calculated. Then we will run a simulation for 1000 runs and get average bias over all runs. Finally, we would iterate over participants and get populatio bias. For item-gist bias, they would be a slight adjustment on how we sample angular distance. Now, the distribution will not be uniform and probability on sampling each angle bin (we bin 360 deg. angular space into 200 bins) will be depending on how close it is to the reported center. 

Statistics

To test how gist and item  memory errors change over time, we would perform 3 (time interval : 24 hr, 1 week, 1 month) x 2 (item memory, gist memory) aligned ranks transformation ANOVA. Futheremore, we will use two-tailed Mann-Whitney tests to compare error change between groups
To compare whether observed bias is different from simulated item-only bias over time, we conducted a 2 (session: Session 1 vs. Session 2) x 3 (delay groups: 24 hr, 1 week, and 1 month) ANOVA. Next we will use two-tailed paired t-tests for post-hoc comparison. 
Lastly, we will use the same statistical tests 2 x 3 ANOVA and two-tailed pair t-tests to determine whether observe bias become more similar simulated gist-based bias overtime. 


### Reliability and validity

The method to measure an error is calculating euclidean distance on x and y-axis. It has been used widely in spatial memory research and has a validity. However, the reliability in this study might be lower than other research as they only measure memory for each location once. So it is more likely to have a noisy estimation of memory from single measurement. 

Normally, the measurement of memory bias can be vary. Some studies use a proportion of response that is biased toward other items. Other studies might flip the sign of error based on the direction of bias and calculate circular mean of error distribution and see whether a mean is significantly different from 0. In this study, they calculate bias  by using the difference between the Euclidean distance from true item location to true gist location and the Euclidean distance from reported item location to true gist location divided by the Euclidean distance from true item location to true gist location. It is more similar to the first method but here they also scale bias so it should be affected less by any outliers. The only concern here is that the reliability might be low as previously mentioned. Another concern is that there is no baseline to compare bias. Therefore, they use simulated bias in order to compare whether the bias become closer to gist overtime.

### Differences from Original Study

Instead of collecting data onsite like in original paper, we collect data online via SONA system. In doing so, we make the change so that the screen size remains the same across all computers by setting canvas size as 1200 * 640 pixels (1280 * 800 pixels in original paper). We also increase error threshold from 80 to 160 pixels in training phase 3 due to feedback during pilot. 

### Methods Addendum (Post Data Collection)



#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	


### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
